version: "3.1"

services:
  db:
    container_name: database
    image: sameerbsn/postgresql:10-2
    environment:
      PG_PASSWORD: $DB_PASS
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./pgdata:/var/lib/postgresql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    volumes:
      - .:/src

networks:
  botnet:
    driver: bridge